### ISSUE TITLE
Real Time display does not load

### ISSUE THREAD

**Issue by Sebi380** [Yuubari/KanColleViewer#14]
Hello the Real time Display ist working anymore.
It shows only start screen with Informations and Settings
Bottom left Corner its says waiting for Kancolle to start but kancolle is already running
Need really help

Hope you can Help me

**Comment by Houraisen** [comment]
I think im also having the same problem...im already in the game itself but it just shows informations and settings with waiting for Kancolle to start. Maybe its cause of the new patch that just got implemented after the maintenance? Hope you can help :)

**Comment by Yuubari** [comment]
Fixed in 4492aacc9b0b886dd81ef5e4c5346fb232a5c5f5.

**Comment by Houraisen** [comment]
Thank you so much!!
