### ISSUE TITLE
New version opens then instantly closes?

### ISSUE THREAD

**Issue by TyrantHead** [Yuubari/KanColleViewer#16]
Hi Yuubari,

When I launch the new v4.2.4, it will launch then instantly close itself.

This is the error message:

> http://puu.sh/o2kr3/7dd7288131.png

Any clues? Thanks.

**Comment by Yuubari** [comment]
Which version of Windows are you using and what is the version of your .NET framework? Did 4.2.0 work before?

**Comment by TyrantHead** [comment]
I'm using Windows 7 SP1 64-bit, .NET framework 4.6.1, and yes v4.2.0 worked before.

I took a screenshot of the error message, it should be clearer to read I think:
http://puu.sh/o2kr3/7dd7288131.png

**Comment by Yuubari** [comment]
Try removing the TaskbarProgress plug-in (in the plugins folder).

Also, for future reference, error.log is a text file. You can just use pastebin.com or something like that to share the text itself.

**Comment by TyrantHead** [comment]
That didn't work.

Here's the pastebin: http://pastebin.com/2eDp3qEg

I know it's not your fault so you don't have to burden yourself with this issue. It's likely some problem on my end if others' KCV is working. I tried it on my laptop and it works, so it's likely an issue with my computer. Maybe I'll look into using another viewer.

Regardless, thanks for your concern Yuubari.

**Comment by Yuubari** [comment]
Now that I think of it, 4.2.0 did not support progress indicators yet (and my internal 4.2.3 build was not published) so the issue might be with Grabacr's code implementing said support and being incompatible with certain configurations.

**Comment by TyrantHead** [comment]
Sorry Yuubari to bother you again, I noticed v4.2.0 doesn't work (same problem), meanwhile v4.1.7 works fine.

**Comment by Yuubari** [comment]
Can you check if [Grabacr's 4.2.4](https://github.com/Grabacr07/KanColleViewer/releases/tag/v4.2.4) works for you?

Also my previous statement is likely incorrect as that task-bar stuff is a pretty major feature and I must have mistaken the releases. 4.2 was probably the one that added it.

**Comment by EvilCommie** [comment]
Had the same issue since 4.2. Window just flashes up then closes immediately. Running Windows 7 SP1 x64, .Net 4.6.1.

http://pastebin.com/xY6EVe7w

Grabacrs latest release gives me the same thing:
http://pastebin.com/Un1HG0R0

Gakada v3.8.2r562 works.

Removing the taskbar plugin did not help.

**Comment by Yuubari** [comment]
**Can someone with this issue please check if Grabacr07's build works on their system?** I mean Grabacr07's, not gakada's, because gakada's is completely different. I even linked the releases page in my response above. Maybe that response does not display properly? I'll repost the link then: please check if [this build](https://github.com/Grabacr07/KanColleViewer/releases/tag/v4.2.4) works on your machine.

**Comment by Yuubari** [comment]
OK I need to calm the heck down.

If Grabacr07's build has the same issue, please report it to him as this is an upstream issue.
