### ISSUE TITLE
question about KCV 4.2.4

### ISSUE THREAD

**Issue by roanyop** [Yuubari/KanColleViewer#17]
1-its just me or KCV 4.2.4 load very slow?
i tessed my net on IE its seem having no problem, 
but inside KCV its takes allmost like 10~15min to fully load.
that not include the loading each battle/tab takes 10sec longer than normal.

2-is there any plugins that 4.2.4 can show the droplist and construction log? like ver3.8.2r557
or i missed something since its in JAP language, plz do teach me about it.

**Comment by Yuubari** [comment]
I have no idea why it is slow for you.

You can switch it to English. There is a logger plug-in bundled with KCV.

You can use 3.8.2r562 from gakada.

**Comment by Yuubari** [comment]
(Also before reporting issues with slow loading etc. please test with Grabacr's original build first.)

**Comment by roanyop** [comment]
allright, thx for advice, did 3.8.2r562 from gakada can use for the new april issue?
last time i using  ver3.8.2r557 but no update and no information about my fleet open up due to new API

**Comment by roanyop** [comment]
oh yea, any quick link for gakada work? that gona be a big help

**Comment by Yuubari** [comment]
Have you tried, you know, [his repository](https://github.com/gakada/KanColleViewer)? I mean, it's probably impossible to find but still.

**Comment by roanyop** [comment]
was looking for gakada works till now..
for now..hahaha.... i try to find em in serchbar but nothing comeout..lol that y.
btw, thx for the help Yuu
