### ISSUE TITLE
New Version of KCV is not Displaying the Game Correctly 

### ISSUE THREAD

**Issue by Michea19509** [Yuubari/KanColleViewer#18]
It's just show the website and wouldn't go to the flash game itself

**Comment by Yuubari** [comment]
That doesn't tell me anything. Which part of the website does it show? What is the URL? There also had not been any new versions since April the 1st.

**Comment by Omegaxis8009** [comment]
The site does not load at all, it's just completely white.

On May 28, 2016 5:49 PM, Yuubari notifications@github.com wrote:

That doesn't tell me anything. Which part of the website does it show? What is the URL? There also has not been any new versions since April the 1st.

**Comment by Yuubari** [comment]
You may try reading [the part of the FAQ about “completely white” screens](https://github.com/Yuubari/KanColleViewer/wiki/Frequently-Asked-Questions#instead-of-the-game-i-only-see-white).

In 99.99% of the cases this is a problem with your OS, browser or the Flash plug-in.

**Comment by Michea19509** [comment]
I wasn't url but I figure it out the url was show about:blank on it

**Comment by Michea19509** [comment]
It was showing about:blank on the url instead of http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/

**Comment by Yuubari** [comment]
This is not a KCV issue then. Most likely KCV cannot connect to DMM so it waits for a time-out; there is nothing I can do about connexion issues on your side.

**Comment by Michea19509** [comment]
It was showing about:blank on the url instead of http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/
