### ISSUE TITLE
Drop ship

### ISSUE THREAD

**Issue by OokamiNeko** [Yuubari/KanColleViewer#2]
Can i suggest you add a dropped ship feature? It will be very convenient if it were to be added.

**Comment by Yuubari** [comment]
Please explain what is a “dropped ship feature”. All drops are already logged to a CSV file provided you have the Logger plug-in running.

**Comment by OokamiNeko** [comment]
It shows what ship you get after battles during sorties

**Comment by Yuubari** [comment]
You can probably implement that as a plug-in.
