### ISSUE TITLE
Frequent hangs and catbombs

### ISSUE THREAD

**Issue by geitentoren** [Yuubari/KanColleViewer#22]
Hi,

I'm experiencing problems with frequent hangs on loading and subsequent disconnects in the game in version 4.2.7 since a few days. This seems to occur on any action that requires loading. Trying an older version did not resolve the issue.

I'm running a non-overclocked Win10 desktop with .NET 4.6 and the latest Flash updates. I can reproduce the issue on a separate Win10 device. The problem does not exist in Internet Explorer itself, so it does not seem to be a network issue. The issue persists after clearing the cache and deleting all application files and redownloading them.

Any idea how to troubleshoot this further?

**Comment by Yuubari** [comment]
Could you check if the issue persists in Grabacr07's builds?

**Comment by geitentoren** [comment]
Hi,

Yes, this seems to occur in Grabacr07's build as well.

**Comment by geitentoren** [comment]
Turns out my router was on the way out after all, it just didn't manifest in any other ways. Thanks.
