### ISSUE TITLE
Having issues with Quest translations

### ISSUE THREAD

**Issue by nynk114** [Yuubari/KanColleViewer#23]
Sup, just having trouble with translations for quests (they're all showing up as "unknown") quests when I have them selected. I tried deleting the files in AppData\Roaming\Smooth and Flat and AppData\Local\Smooth and Flat and Smoot_and_Flat. Tried toggling between different languages with the same result. Tried re-extracting files from the original download folder, no effect. 

Also attached error log if relevant.
[error - Copy.txt](https://github.com/Yuubari/KanColleViewer/files/392170/error.-.Copy.txt)

**Comment by Ech0Sierra** [comment]
Noticed this with the latest update, the only way to properly load quests is to scroll through the all section until they pop up.

**Comment by nynk114** [comment]
Nup, tried that and they're still not turning up (despite selecting the tab which displays quests in progress)

**Comment by Yuubari** [comment]
This is really weird and I am unable to reproduce this yet. Does this also happen with Grabacr07's original builds?

**Comment by nynk114** [comment]
I just downloaded and tried it and still not getting anything.

Interestingly enough, on grabacr's 4.2.7 I'm getting errors on the "Plugins"section for the following files:

Counter.dll
EventMapHPViewer.dll
TaskbarProgress.dll
WindowsNotifier.dll

Each with the following error:
System.IO.FileLoadException: Could not load file or assemply '[PLUGIN NAME], Version=x.x.x.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

**Comment by Yuubari** [comment]
I will try merging in some code updates later and upload the results for you guys to test.

**Comment by nynk114** [comment]
Oh shit dont mind me I just realised what the issue was.

IM SORRY FOR WASTING YOUR TIME. It was the going through the "all section" which confused me - I thought you just had to go to the quests in progress section.
And so I wasted everybody's time.

I have to offer my my sincerest apologies. I misunderstood and did all this. Please forgive me TTwTT

**Comment by Yuubari** [comment]
Yes, the “All” section is where you can get all of them and KCV can parse it correctly.

In other sections the server provides the number of active quests, but only a subset of them, and since KCV blanks out its quest list every time when a new list is received, this happens.
