### ISSUE TITLE
Equipment names are not visible in Fleet tab

### ISSUE THREAD

**Issue by Tokimonatakanimekat** [Yuubari/KanColleViewer#24]
There are no equipment names whenever I hover over a piece of equipment in Fleet display, empty black square is displayed instead.

![kcverr](https://cloud.githubusercontent.com/assets/18497148/17407564/6ba0dbd8-5a70-11e6-89f0-2f186bb3607f.png)

**Comment by Yuubari** [comment]
Fixed in fa8a74cbbf21053d20ee281ec76290fb9e4cd8d6.
