### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by drhomieg** [Yuubari/KanColleViewer#26]
I've recently been unable to use KCV at home.  It is usually stuck loading a screen, or during one of the game refreshes.  I haven't changed anything with it before, and I've been using it for almost a year now.  The game runs fine on IE and KC3 has no problems.

However, when I switch my internet to my mobile hotspot, KCV works fine.  I have Win10 and there have been some updates in the last few days, should i be disabling any of them?

On another note, the BattleInfo stops working in 6-5 when there is an Abyssal Combined Fleet.

**Comment by Yuubari** [comment]
I'll try releasing an updated build soon-ish but I doubt it'll fix your primary issue.

BattleInfo simply needs an update, and from what I see, veigr (the plug-in's developer) has not yet released one.

**Comment by drhomieg** [comment]
I can open KCV now, but the extra tabs aren't showing since the new update, it only shows the Information and Settings tabs.

**Comment by Yuubari** [comment]
I have released an update, it should work fine.
