### ISSUE TITLE
KCV Launches game but doesn't display connection.

### ISSUE THREAD

**Issue by stargatedalek** [Yuubari/KanColleViewer#27]
http://pre14.deviantart.net/ec3d/th/pre/f/2016/294/9/8/kcv_glitch_by_michell_vall-dalrobl.png

Earlier today the build of KCV I was using inexplicably stopped working and closed with the general Windows "X has stopped working" message even after clearing cache or setting cookies. I was relieved to see there was a newer build, and so assumed that was my issue, but upon loading KanColle in the new build the game works fine but KCV no longer can tell it's connected. I tried clearing the cache and using the cookie function again but no luck. 

Windows has sent out a few updates recently but I don't think any between the last time I played and today, although AMD is telling me to update right now so I'll give that a shot.

_edit_
As expected AMD update had no effect. KCV still manages to launch and run the game fine so it's not like this is a huge issue, I miss the quick mute more than anything.

**Comment by Yuubari** [comment]
I'm afraid this may be an issue on your side. Have you tried removing the AppData folders referenced in the FAQ under “My PC crashed” etc.? Both the underscore and white-space ones.

**Comment by stargatedalek** [comment]
Unfortunately that didn't change it, thanks for the help anyway mate.

**Comment by Gylthas** [comment]
I'm having the same problem and don't know what to do about it.
Until today it worked just fine.

EDIT: Tried changing to an older version that worked for me before, but it keeps doing the same.

**Comment by Yuubari** [comment]
The game was updated.

I cannot update KCV right now due to health issues; I'll release a new version in a few days.
