### ISSUE TITLE
KCV no longer displays info after new event update (11/18/2016)

### ISSUE THREAD

**Issue by advarcher** [Yuubari/KanColleViewer#28]
KCV no longer displays the information available in-game after the new Fall event update on 11/18/2016

![kancolle-11-18-2016](https://cloud.githubusercontent.com/assets/19716371/20452341/4376b958-adbc-11e6-822e-e3edcadbe89b.png)

**Comment by eD1s0n** [comment]
same issue here. clearing cache does not fix

**Comment by AndySun25** [comment]
Since I don't think this repo is being actively updated anymore, I've forked it and merged upstream changes.

https://github.com/AndySun25/KanColleViewer/releases

**Comment by Yuubari** [comment]
Fixed in 1b8fa41217be88b4e676cc6bf6e36610957358f5, a new release is up now.
