### ISSUE TITLE
Fleets box on Overview tab issue

### ISSUE THREAD

**Issue by Federer343** [Yuubari/KanColleViewer#29]
The issue I'm having, is when I have ships with longer names in my fleet, the fleets box on the overview tab has to generate a scroll bar in order for me to see the whole thing.  The problem that comes with that is that if the ship's name is long enough, I have to choose between being able to see the ship's name or it's morale.

[An extreme example can be seen here.](http://i.imgur.com/xyG16gE.png)  With Chiyoda CVL Kai2 taking up a huge chunk.

My suggestion would be to make it so the names of ships can only take up so much space, until after a certain point they go under the rest of the information displayed, [as I have shittily displayed here](http://i.imgur.com/Dkj91vs.png).  Another probably easier solution would be to just reduce the text size of a certain ship if the ship's name gets too long, again, [shittily displayed here](http://i.imgur.com/SRZSHJz.png).  Either way it would probably do the trick.

It's also worth noting that this problem is likely restricted to people who play with the game arranged as I have it, [displayed here](http://i.imgur.com/EDkJI9k.png).  With the program window pulled tightly against the game window, so I can do stuff in the other 3/5 of my screen while playing.  And also I run at 1920x1080, so the problem may not exist for other resolutions.

Thanks for any help you can provide.

**Comment by Yuubari** [comment]
A good while ago I had it working approximately the way you illustrate in the picture for your first suggestion as the box had no scrollbars whatsoever. (For future reference: you can drag and drop screenshots into GitHub text editor; they will be hosted on GitHub and stay fresh forever.)

However, in a later build Grabacr07 introduced these scrollbars and sadly WPF does not allow for a decent way to implement trimming. I will see what I can do about it, but chances are pretty slim.

**Comment by Federer343** [comment]
Alright cool.  Thanks for the help.

If it's of any assistance, I used to use gakada's fork instead of this one.  And I believe he had it working similarly to the way I described, he just hasn't updated in a long while.  But at the very least it's doable, either that or he's just working with a vastly older version.

**Comment by Yuubari** [comment]
Does not look like it from the source: https://github.com/gakada/KanColleViewer/blob/master/Grabacr07.KanColleViewer/Views/Contents/Fleets.xaml#L138

See c7f33afef31407255082d732dafed7a4e412348a for my change that introduced name trimming.

I think I was the only one who ever bothered to add text trimming in that UI element.

**Comment by Federer343** [comment]
Ahh I was actually wrong about the text trimming, I couldn't check because gakada's version wasn't loading for me, but now it suddenly is.  He got past it by just adjusting the sizes of some of the other things on the overview tab.

![66](https://cloud.githubusercontent.com/assets/13668017/20468229/1d9bbda6-af5a-11e6-8441-8879cb7c578d.png)

Looks like he just shrunk everything else and scrunched some stuff closer together to the point where the fleet box was just really big, looks like the text size is just a bit smaller too and also more clumped together.

**Comment by Yuubari** [comment]
To be honest, this fork's primary purpose is to provide localisation and translations. Due to my lack of experience with C# and WPF, I try to minimise the changes I introduce into the source code so it's easier to merge later. The other issue is that since my fork supports different languages, and I keep Japanese available as a UI language, I have to keep the fonts as is, or the kanji will become barely readable.

Another issue I encountered when trying to solve this issue is that WPF Dynamic Fonts seem to not work correctly, so I could not make it use Arial Narrow for Latin characters while retaining Meiryo for CJK.

**Comment by Federer343** [comment]
That's perfectly fine.  I still prefer this fork for its stability and translation updates that are usually on time.

Just offering enhancement suggestions if they're even possible.

Thanks for maintaining this fork.
