### ISSUE TITLE
Glitch causes undue cpu strain and unplayability

### ISSUE THREAD

**Issue by todkapuz** [Yuubari/KanColleViewer#29]
With certain ship names the overview screen goes into an infinite resizing loop that drains all available CPU time for the processes as it resizes, decides it can fit more, resizes, decides its too big, resizes smaller etc...   making the whole thing unresponsive and unplayable.    It doesn't matter if you switch off the over-view tab, it appears to continue to try to do the resizing even when not on the screen. Sometimes it can be resized to stop the oscillation between sizes, but often it is too unresponsive to notice the click. Only full-screening it stops the problem.  It drives it to 1 frame in 10 seconds when driven across a remote desktop session. Upside: ships are always ready to sortie again. I've had this happen a few times in the past... but its becoming more regular.   Visual example: https://www.youtube.com/watch?v=Dc34E4OdBtg

**Comment by pwjusticed** [comment]
Err apparently the problem still persist, a little differently, upon a bit of window stretching.

Start with 100% and an unstretched viewer's width.

These 3 ship :
Kongou Kai - 4 digit exp, below 100 morale.
Ise Kai or Yamato Kai - 4 digit exp, has 100 morale.
Nagato or Haruna or Suzuya - 3 digit exp, below 100 morale.

Just stretch the viewer's width a little bit and... Voila!

Adding some additional ship may nullify the bug. As example adding Fusou will still triggering it, however adding Yamashiro (has ... in the viewer's name) will nulify the bug.

**Comment by Yuubari** [comment]
In the new version Kameya added a scrollbar to the fleet pane in Overview. I've merged the changes, but this will result in ships like Chitose making it scroll a lot.

**Comment by todkapuz** [comment]
Scroll bars have completely resolved all issues for me.  Thanks for your work.
