### ISSUE TITLE
Quest Display

### ISSUE THREAD

**Issue by Nashical** [Yuubari/KanColleViewer#30]
Hi Yuubari,
I've noticed that in the 4.2.4 patch, the quests that are displayed in overview can be updated by clicking on the Currently Active tab in Quests. After moving to the 4.2.9 patch, my quests in overview won't display at all; it's just a blank box that says Quest. So I compared some files in the 4.2.4 patch to this one and I moved a missing file (Or what I thought was missing) back into this patch. But now in order to refresh the Quests section, it changed to having to scroll through your quests in the All tab. Is there a way to change this back or was this a change made based on preference?

**Comment by Yuubari** [comment]
There were no changes made to the quests display logic. As it has been mentioned previously, the only way to get the quest list 100% right is to go through all pages of the “All quests” category because that's how the game's API works. Anything else is wonky.

Checked just in case, my copy (without copying/moving any files) displays quests correctly if the aforementioned approach is used.

**Comment by Nashical** [comment]
Huh, interesting... I can confirm that using the Currently Active tab can refresh the quests in the previous patch but it's strange that since you said you didn't change anything it doesn't work like this anymore...

**Comment by Yuubari** [comment]
I am seriously a bit tired of explaining why this stuff works in this way. There has been a previous report, #20, regarding this exact problem.

To reiterate: _the game does not keep any kind of quest data client-side._ Everything related to quests is processed on the server. The quests UI displays active quests on different pages, and each page is a different set. _There is no data package that includes all active or all available quests;_ KCV assembles these by analysing multiple pages, and this cannot be done without the user manually switching between pages.

As there is no reliable way to tell if a certain quest filter has all the quests you have active, or if there were no changes to available/completed/active quests, KCV has to rebuild the quest list _every single time you open the UI to any of the filters to make sure the page-based assembly is not messed up._

**Comment by Yuubari** [comment]
The active quests tab may work. It may not work. It's _undefined behaviour_ for KCV, because the active quests tab does not provide information about all available quests and KCV needs that information to build its daily/weekly lists.

**Comment by Nashical** [comment]
Thanks a lot Yuubari, sorry for the inconvenience!
