### ISSUE TITLE
Where is snapshot button

### ISSUE THREAD

**Issue by highlizard** [Yuubari/KanColleViewer#31]
![clipimage](https://cloud.githubusercontent.com/assets/19148717/20472068/0c1205ea-affa-11e6-9b72-ab3328c27d91.jpg)

I find snapshot but not found
Where is snapshot button ?

**Comment by Yuubari** [comment]
Under the main game display.

![image](https://cloud.githubusercontent.com/assets/7750448/20474453/af0a6e22-afd7-11e6-948c-8149883f5771.png)

I have no idea how exactly did you manage to break it.

**Comment by Nashical** [comment]
I have the same problem, you just need to drag the bottom of your window lower.

**Comment by highlizard** [comment]
Ok I will try it
