### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by drhomieg** [Yuubari/KanColleViewer#32]
will we get a quality of life update?  I really enjoy using your kcv

maybe new equipment?
new translated ship names?

updated battle predicter?

**Comment by Yuubari** [comment]
Currently on hold due to lots of work, apologies.

Once I'm done with that, I'll publish an updated build.

**Comment by Federer343** [comment]
Honestly I'd just wait for the next event to start in a month~ or so, to get all the new translations in.

**Comment by Yuubari** [comment]
4.2.10 is up.
