### ISSUE TITLE
Quest tracker does not update

### ISSUE THREAD

**Issue by repounited** [Yuubari/KanColleViewer#33]
Hey, when I try to get the quest tracker to update, it'll only show unknown quests. I have to manually go through all the pages of my quests, rather than just going to my active quests tab within kc, so I was wondering if you know how to fix this? Thanks!

**Comment by Yuubari** [comment]
Please refer to #30?

**Comment by repounited** [comment]
Hmm alright, I read through the thread and understand the problem. Thanks
for the quick reply!
