### ISSUE TITLE
Sortie logging doesn't work

### ISSUE THREAD

**Issue by Teitoku** [Yuubari/KanColleViewer#33]
Throws System.ArgumentNullException
Itemyard.cs:155

Will update with more info as I find it.

**Comment by Yuubari** [comment]
I'm not sure what “sortie logging” is. As of right now, KCV does not support the logging of anything besides drops, construction, development and changes of the materials' amount. All of these work fine.

Could you elaborate?

**Comment by Teitoku** [comment]
If I recall, the logger supports logging ship drops from sortieing `private void BattleResult(kcsapi_battleresult br) [Logger.cs:77)]`, where if you get a ship dropped while on a sortie, it logs it along with what map and node, and the rank you got.

**Comment by Yuubari** [comment]
Yes. To quote my own log,

```
2015-01-05 01:47:10,Shikinami,World 1-5,Main Trade Attack Fleet (Boss),S
2015-01-05 01:53:18,Shigure,World 1-5,Reconnaissance Submarine,S
2015-01-05 01:54:48,Samidare,World 1-5,Submarine Fleet Group A,S
2015-01-05 01:58:57,Sazanami,World 1-5,Submarine Fleet Group C,S
```

Could you point out what exactly does not work about it? Since the 3.0 merge I've gotten zero reports regarding ship drop logging, and it seems to work fine for everyone.

**Comment by Teitoku** [comment]
It doesn't log any drops with your latest build. Building from source and attaching a debugger shows that it throws `System.AgumentNullException` on [Itemyard.cs:155](https://github.com/Yuubari/KanColleViewer/blob/master/Grabacr07.KanColleWrapper/Itemyard.cs#L155) when a drop happens and never hits the logging code.

Tested on 1-1.

**Comment by Yuubari** [comment]
I'm using my latest build right now (I always run the most current builds) and logging works fine. If there was something wrong with logging in any of the releases I'd most probably have gotten numerous reports on IRC by now.

I'm presently unable to reproduce this.

**Comment by Teitoku** [comment]
I did some more testing, and this reproduces consistently on 1-1. Drops on 2-1 log correctly, so it seems like it's an issue with the newbie maps.

**Comment by Yuubari** [comment]
7e219aa4bb7cbb358c20a417be3db6fbd385a6f3 might possibly fix this.
