### ISSUE TITLE
Untranslated quests

### ISSUE THREAD

**Issue by mehkanik** [Yuubari/KanColleViewer#34]
New player, found a few quests still untranslated.

```
  <Quest>
    <ID>105</ID>
    <JP-Name>軽巡２隻を擁する隊を編成せよ！</JP-Name>
    <TR-Name>軽巡２隻を擁する隊を編成せよ！</TR-Name>
    <JP-Detail>軽巡洋艦２隻を擁する高速艦隊を編成せよ！</JP-Detail>
    <TR-Detail>軽巡洋艦２隻を擁する高速艦隊を編成せよ！</TR-Detail>
  </Quest>
  <Quest>
    <ID>115</ID>
    <JP-Name>第２艦隊を編成せよ！</JP-Name>
    <TR-Name>第２艦隊を編成せよ！</TR-Name>
    <JP-Detail>二つ目の艦隊、第２艦隊の旗艦を指定して、第２艦隊を編成せよ！</JP-Detail>
    <TR-Detail>二つ目の艦隊、第２艦隊の旗艦を指定して、第２艦隊を編成せよ！</TR-Detail>
  </Quest>
  <Quest>
    <ID>254</ID>
    <JP-Name>「軽空母」戦隊、出撃せよ！</JP-Name>
    <TR-Name>「軽空母」戦隊、出撃せよ！</TR-Name>
    <JP-Detail>軽空母1～2隻、軽巡1隻、駆逐艦3～4隻の艦隊でカムラン半島の敵を撃滅せよ！</JP-Detail>
    <TR-Detail>軽空母1～2隻、軽巡1隻、駆逐艦3～4隻の艦隊でカムラン半島の敵を撃滅せよ！</TR-Detail>
  </Quest>
  <Quest>
    <ID>215</ID>
    <JP-Name>第２艦隊、出撃せよ！</JP-Name>
    <TR-Name>第２艦隊、出撃せよ！</TR-Name>
    <JP-Detail>新たに編成した「第２艦隊」を出撃させよ！</JP-Detail>
    <TR-Detail>新たに編成した「第２艦隊」を出撃させよ！</TR-Detail>
  </Quest>
  <Quest>
    <ID>617</ID>
    <JP-Name>「伊良湖」の準備</JP-Name>
    <TR-Name>「伊良湖」の準備</TR-Name>
    <JP-Detail>「工廠」で不要な装備アイテムをいくつか「廃棄」して、新型給糧艦召喚の準備をしましょう！</JP-Detail>
    <TR-Detail>「工廠」で不要な装備アイテムをいくつか「廃棄」して、新型給糧艦召喚の準備をしましょう！</TR-Detail>
  </Quest>
</Quests>
```
I'll be machine translating them so I have some sort of idea until a proper translation comes through. Thanks for the viewer, it's been mighty helpful (and the only one that seems to work for me) so far.

**Comment by Yuubari** [comment]
Please explain how exactly are these not translated:

https://github.com/KCV-Localisation/KanColleViewer-Translations/blob/master/Quests.xml#L32
https://github.com/KCV-Localisation/KanColleViewer-Translations/blob/master/Quests.xml#L102
https://github.com/KCV-Localisation/KanColleViewer-Translations/blob/master/Quests.xml#L452
https://github.com/KCV-Localisation/KanColleViewer-Translations/blob/master/Quests.xml#L690
https://github.com/KCV-Localisation/KanColleViewer-Translations/blob/master/Quests.xml#L1075

I'm eagerly awaiting your comments.

**Comment by mehkanik** [comment]
1. They're not translated in my file, which according to your tool, is apparently up to date.
2. I am.
![fe7btjg 1](https://cloud.githubusercontent.com/assets/3248337/5769127/6cf265f0-9ce5-11e4-94aa-01c5a67da85a.png)
/FE7bTJg.png
3. Because I'm a human being and lack didactic memory, so I'm can't always remember the minutia of every FAQ for a tool I happen across and want to try. I remember reading the FAQ several days ago, mid work-week and the keywords I remember are "Submit issue if things are missing". I apologize for my ill-founded attempt at being helpful.

I don't mind if you're curt or whatever else, but I think the complete assumption of fault on my part is a little unwarranted. Sure, I could've probably reread that FAQ just to be certain *where* to post, but I also suppose if your tool is enabled to automatically update... it should probably do that. Any idea why it doesn't?

**Comment by Yuubari** [comment]
Would you mind kindly downloading the newest version from https://github.com/Yuubari/KanColleViewer/releases and using that? I imagine it might help resolve this issue. To quote the repository's main page, “Old versions (check the Releases section to verify which version is the current) are not (and will not be) supported.”

The 2.x versions have been abandoned since August 6th.

**Comment by mehkanik** [comment]
Yeah, that solved it. I think I'm going to make sure to steer clear of issue trackers after working several days in a row.

**Comment by Yuubari** [comment]
I do apologise though, I never imagined people still use the old 2.x builds, let alone Zharay's, so I didn't think of the “update URLs pointing to the original repository” possibility.
