### ISSUE TITLE
BattleInfoPlugin source code

### ISSUE THREAD

**Issue by SquidFish** [Yuubari/KanColleViewer#34]
Hi, the BattleInfoPlugin is not included in the source code released.
 
Can you upload it too?

**Comment by Yuubari** [comment]
I am pretty sure it is available at [its own repository](https://github.com/Yuubari/BattleInfoPlugin)?

**Comment by SquidFish** [comment]
Oh must've missed that.
Thank you.

**Comment by SquidFish** [comment]
I'm sorry about just now I was being unclear.
What i'm referring to is the one that you included in the "KanColleViewer! 4.2.10: Ask Vigne Maybe" download section.
It's called "BattleInfoPlugin-mod-lib-20170507.zip"

**Comment by Yuubari** [comment]
Yes, it's in the BattleInfoPlugin repository, the localisation (default) branch.

**Comment by SquidFish** [comment]
The Vigne version looks like this.
![vigne](https://user-images.githubusercontent.com/32428830/31138916-8f023294-a8a2-11e7-956f-0208edfc8ae4.PNG)

While the one that is in the BattleInfoPlugin repository is like this.
![notvigne](https://user-images.githubusercontent.com/32428830/31138950-b03bca1a-a8a2-11e7-9b23-359180b4edc3.PNG)

**Comment by Yuubari** [comment]
Yeah I probably used some other fork there. Try https://github.com/Yoctillion/BattleInfoPlugin — I think that's the one.

**Comment by SquidFish** [comment]
This is the one i'm looking for. Thank you again.
