### ISSUE TITLE
Entering API link downloaded the flash file instead

### ISSUE THREAD

**Issue by Nyoropyon** [Yuubari/KanColleViewer#35]
Hello,

So I haven't used KCV for months, and when I fired up KCV again today, it told me to update to the latest version, 3.4.0.1 (My current version was 3.3.0 r7 IIRC). So I did just that.

Then, I went about the usual procedure of obtaining an API link, pasted it into the address bar, and then there was what appears to be a typical download file dialog of Internet Explorer.

Here's the bug(?) in action:

![kcverror](https://cloud.githubusercontent.com/assets/10725106/5918720/6ef7352e-a65e-11e4-9cb4-0b5b79a9d76b.JPG)

**Comment by Yuubari** [comment]
https://github.com/Yuubari/KanColleViewer/blob/master/FAQ.md#instead-of-showing-the-game-kcv-tells-me-to-download-something

**Comment by Nyoropyon** [comment]
Ah, I'm sorry... I missed the FAQ >_>" anyway, it runs properly now; I installed Flash Player directly from IE, and now the plugin shows up in the add-ons dialog.

...Though I wonder why this only happened now. It wasn't like this before...
Anyway, thanks for the help!
