### ISSUE TITLE
KCV not responding

### ISSUE THREAD

**Issue by Katsuga** [Yuubari/KanColleViewer#4]
Hi,

Just recently I cannot play Kancolle using KCV anymore. Every time I paste the API link to the address bar and press Enter, the KCV stop responding and close. Play on dmm using KCV produce the same result.

I try clear cache, cookies of Chrome and IE, but nothing's changed.

Can you help me with this? Using KCV over a year and I don't want to change to another one

**Comment by cpang6** [comment]
I am having this same problem all of a sudden. I tried cleaning up DirectX but that didn't work either.

**Comment by unicron02** [comment]
Same issue in Windows 10 - just crashes the moment it tries to load the page/flash files after logging in.  Windows does not provide any crash code/error message.  This happened after a Windows update was applied earlier in the day.

**Comment by unicron02** [comment]
Uninstalled the following update and KCV works:
Security Update for Internet Explorer Flash Player for Windows 10 Version 1511 for x64-based Systems (KB3132372)

**Comment by Yuubari** [comment]
See Grabacr07/KanColleViewer#176.

**Comment by Yuubari** [comment]
[KB3133431](https://support.microsoft.com/en-us/kb/3133431) addresses this issue.
