### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by vilenia** [Yuubari/KanColleViewer#40]
I keep getting the error cat on KCV specifically ever since I updated my version of KCV. I'm not having this issue with other methods in regards to playing the game (VPN, and such work just fine). My internet connection is fine, I've tried clearing the cache, setting region cookie, etc. KCV just refuses to let me past error cat and I'm not really sure what the problem is.

**Comment by Yuubari** [comment]
Did you check if it still disconnects when opened in your Internet Explorer without VPN (if you've set the region cookie, it applies to MSIE too)?

**Comment by vilenia** [comment]
Aah, yes its disconnecting in IE as well with VPN (My main browser is typically firefox).

**Comment by Yuubari** [comment]
I'm afraid this is out of score of this project. The viewer uses Microsoft Internet Explorer browser control to run the game.

Make sure that you have the latest version of Internet Explorer and Flash Player.
