### ISSUE TITLE
Ship names and class, notifications settings, guns and quest names and descriptions won't translate in english language. 

### ISSUE THREAD

**Issue by CaptKelerick** [Yuubari/KanColleViewer#43]
The settings is in the english language, but there some chinese in some places.

**Comment by CaptKelerick** [comment]
I fixed the problem.

**Comment by ifonefox** [comment]
Do you remember how you fixed the problem?

**Comment by CaptKelerick** [comment]
I put here: C:\Program Files (x86)\ and they back to the normal.

**Comment by shyevsa** [comment]
it probably the same case as : 
https://github.com/Yuubari/KanColleViewer/blob/master/FAQ.md#i-pinned-kcv-to-my-taskbar-and-translations-arent-working

in windows 8, this issue affecting pinned taskbar, pinned start menu, and sometimes desktop shortcut as well.
