### ISSUE TITLE
Translations keep getting lost

### ISSUE THREAD

**Issue by senpai-d** [Yuubari/KanColleViewer#48]
For some reason, starting recently, the translations keep disappearing and I'm left with the original text for everything. I tried to update the translations but it says "KCV was unable to download the translations." Also, the versions for the translation are at 0.0.0. I have tried rewriting the xml files with the text that's on the pages but it still does not work. I've tried going back a version and it was working fine until the third open of KCV that it did it again. Language is set to English by the way, and I disabled auto-updates for translations to see if that was the problem, but nothing.
![problem with kcv](https://cloud.githubusercontent.com/assets/11383833/6549978/cecef9a0-c5f3-11e4-815c-c66cb42e9835.PNG)

**Comment by Yuubari** [comment]
Many thanks for reading https://github.com/Yuubari/KanColleViewer/blob/master/FAQ.md#i-pinned-kcv-to-my-taskbar-and-translations-arent-working and below before submitting this issue.
