### ISSUE TITLE
Unable to scroll when mouse is over ships under the overview.

### ISSUE THREAD

**Issue by mikenzb** [Yuubari/KanColleViewer#50]
It's kinda hard to explain about when my mouse is over the ship list in the overview I'm unable to scroll up or down, however when I move it to the side to the quests/repairs area I'm able to freely scroll up and down.

![areakcv](https://cloud.githubusercontent.com/assets/5982780/6743084/8d3ca3e2-cefa-11e4-901e-a73df30d195f.PNG)
Basically the screenshot shows what area I'm unable to scroll up or down in, everywhere else seems to work fine, only started happening when I updated to the newest version a few ago.

**Comment by Yuubari** [comment]
Ship listing has its own scroll area. This is a change from upstream and it's not considered a bug.
