### ISSUE TITLE
Ship list doesn't show up

### ISSUE THREAD

**Issue by murkis** [Yuubari/KanColleViewer#52]
My ship list is empty, does anyone have an idea what the issue might be?

**Comment by Yuubari** [comment]
You have provided a nearly zero value of information related to your setup.

I'm sorry but I am unable to assist you.

**Comment by murkis** [comment]
Version 3.6.1 rev.7. Absolutely default setup.

**Comment by Yuubari** [comment]
If everything else works, it's either a local bug (which would be the first time ever I heard of something like this) or an issue with the way the server pushes API to you.
