### ISSUE TITLE
Blank screen and CPU load (along with tons of open TCP)

### ISSUE THREAD

**Issue by mlmmt3** [Yuubari/KanColleViewer#53]
When I go to start KCV I get a blank screen for it, and it uses 100% cpu for a couple seconds at a time.
Also, if I check resource manager, KanColleViewer.exe has several hundred TCP connections!

Some other problems I am having now, if it eventually does load a page, it says proxy server not responding even though I do not have it configured to use a proxy server o.O

And perhaps I should mention that I CAN play KanColle in an IE window...

**Comment by mlmmt3** [comment]
https://github.com/Grabacr07/KanColleViewer/issues/139 <seems related to this!

**Comment by Yuubari** [comment]
Well if you want you can try the new build with this issue fixed: https://github.com/Yuubari/KanColleViewer/releases/tag/v3.6.1r8 — get the 3.6.1.8-2 archive. Version number is the exact same but the fix (ref.: 7b2175be5ef7476ea541c4543bbafad5ac6bdec1) is there.

**Comment by mlmmt3** [comment]
Yes, it fixed the problem, and while I do have a firewall, it wasn't doing its job... apparently the IP I got from my ISP yesterday was connected to... something.. because it wasn't a problem until then.
