### ISSUE TITLE
Window unmutes when playback device changes

### ISSUE THREAD

**Issue by Selphos** [Yuubari/KanColleViewer#54]
Minor issue. When plugging in headphones, or using an HDMI to move display/audio to a TV, etc, KCV's mute function fails and the game starts playing audio again until the mute is de- and re-activated.

**Comment by Yuubari** [comment]
That's not a KCV issue, that's a Windows mixer issue. KCV cannot reliably track its playback device or mute status.

**Comment by Selphos** [comment]
Oh. Never mind then, I guess.
