### ISSUE TITLE
KCV doesn't get start showing gameplay info

### ISSUE THREAD

**Issue by BlinkXPoke** [Yuubari/KanColleViewer#55]
Whenever I start KCV, the Information and Settings tabs don't turn into all the relevant gameplay information and tabs after the game starts. It stays stuck in the mode where it's still waiting for KanColle to start, despite being already in the game.

![problem](https://cloud.githubusercontent.com/assets/12022033/7220713/f65ec122-e686-11e4-93fa-dd931b11b151.PNG)

**Comment by BlinkXPoke** [comment]
At the time I write this, this is the latest version.

**Comment by Yuubari** [comment]
https://github.com/Yuubari/KanColleViewer/blob/master/FAQ.md#kcv-shows-the-game-but-the-bottom-or-right-for-the-horizontal-version-pane-remains-in-the-waiting-for-kancolle-to-start-state

**Comment by BlinkXPoke** [comment]
Thank you.
