### ISSUE TITLE
KCW freezes upon start

### ISSUE THREAD

**Issue by Eurofag** [Yuubari/KanColleViewer#57]
Standard KCW! has stopped working error is thrown.

Only experiencing it with 3.7.0 and 3.7.0.1

I'm running Windows in a virtual machine emulated using Parallels but this has never caused an issue.

Also seeing it with the latest Windows 10 DP.

Details:
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	KanColleViewer.exe
  Problem Signature 02:	3.7.0.1
  Problem Signature 03:	554a03ad
  Problem Signature 04:	System.ComponentModel.Composition
  Problem Signature 05:	4.0.30319.34209
  Problem Signature 06:	53489a3b
  Problem Signature 07:	3de
  Problem Signature 08:	c
  Problem Signature 09:	HA2R5VSSKG1RXUACXV143HZFUV1CT25U
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1038
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Eurofag** [comment]
"Clean" install fixed it.

**Comment by Yuubari** [comment]
Please do not use 3.7 with ExperienceCalculator.dll from 3.6, they are incompatible.

**Comment by Eurofag** [comment]
Indeed.
Might be noteworthy in the release notes as I believe I'm not the only one who extracts to the same folder all the time.
