### ISSUE TITLE
swipe left/right on overview crashes app

### ISSUE THREAD

**Issue by hnryirawan** [Yuubari/KanColleViewer#59]
several version ago, it still working. however now it does not work.

**Comment by Yuubari** [comment]
1. Test with the original Japanese KCV build.
2. If it doesn't work, report the issue to Grabacr07, not me.

**Comment by hnryirawan** [comment]
It works with original grabacr07's build and yuyuvn's build

**Comment by Yuubari** [comment]
Fixed in the latest binary release.
