### ISSUE TITLE
Ship girl roster not working as expected

### ISSUE THREAD

**Issue by NicolaosGreene** [Yuubari/KanColleViewer#60]
In previous versions clicking on ship name in the ship girl roster would short them in descending alphabetical order and clicking it again would sort them in ascending alphabetical order. In the current version (3.7.0 rev 3) clicking this sorts the ships by their descending ship ID (e.g. Nagato is 001, Mutsu is 002 and so forth).

**Comment by Yuubari** [comment]
Fixed in the newest binary release.
