### ISSUE TITLE
Fleet info no longer updates between nodes during sortie.

### ISSUE THREAD

**Issue by AndySun25** [Yuubari/KanColleViewer#61]
After 18/05 server maintenance it seems that fleet info (morale, fuel/ammo, hp) is no longer updated after finishing a node during a sortie. It now updates only after the sortie is finished.

**Comment by Yuubari** [comment]
One simple question: why are you reporting this here and not in the main KCV repository? This is an upstream issue…

**Comment by AndySun25** [comment]
Apologies, the thought went over my head.

**Comment by Yuubari** [comment]
Anyway, it was fixed in upstream.
