### ISSUE TITLE
Connection error?

### ISSUE THREAD

**Issue by AliciaMelchiott** [Yuubari/KanColleViewer#65]
So every time I start up KCV, it opens without crashing and does not generate an error log. However, it does not let me get into the game, instead showing a white screen with the following text:

[Fiddler] The connection to the upstream proxy/gateway failed. Closing Fiddler, changing your system proxy settings, and restarting Fiddler may help. 
Error: ConnectionRefused (0x274d). 
System.Net.Sockets.SocketException No connection could be made because the target machine actively refused it 127.0.0.1:8555 

Is this a connection error of some sorts? I'm not so sure what kind of error this is. Much help appreciated.

**Comment by Yuubari** [comment]
It pains me to ask you of this, but would you kindly mind checking your system proxy settings, as FiddlerCore suggests?

If I may suggest, and if that would be not too much of a bother, please kindly open either Internet Options in Control Panel or Internet Options in Internet Explorer's cog menu, go to Connections and press LAN settings (if that is not too arduous a task).

Once there, please remove the checkmark for the “Use a proxy server for your LAN” option. Many, many thanks in advance.

**Comment by AliciaMelchiott** [comment]
Alright, I've managed to fix this. KCV is working normally now. Many thanks.
