### ISSUE TITLE
Ship Rooster images

### ISSUE THREAD

**Issue by tasetase** [Yuubari/KanColleViewer#68]
In the ship rooster, I added ship icons with on-hover card display in my fork. Is there any interest in merging this into your branch ?

**Comment by Yuubari** [comment]
Apologies, but I don't find this an essential feature for the fork.

In my opinion, implementing this as a plug-in would be the best way to go about it. It may even be possible to programmatically add icons and tool-tip images to the existing ship roster window from the plug-in's code.

**Comment by tasetase** [comment]
Have you looked into the plugin solution ? There are no named nodes in ShipCatalogWindow, so assuming I can even access that window, doing anything with it would be a massive hack at best. I don't think a plugin would be possible without modifying the "internal" code to expose the window and it's controls.
