### ISSUE TITLE
BattleInfo

### ISSUE THREAD

**Issue by tensei** [Yuubari/KanColleViewer#7]
BATTLEiNFO says
SwfFormat.dll and ICSharpCode.SharpZipLib.dll is missing

**Comment by Tsukalos** [comment]
[From veigr repository](https://github.com/veigr/BattleInfoPlugin)
[Release](https://ci.appveyor.com/project/veigr/battleinfoplugin/build/artifacts)
The two missing .dll should be in the same folder of the .exe, not the plugin folder,
maybe @Yuubari need to include the two in the next release.

**Comment by Yuubari** [comment]
I'll probably include these, yeah.

**Comment by Yuubari** [comment]
Bundled the plug-in and the DLLs with the updated 4.2.4 release.
