### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by akakishi** [Yuubari/KanColleViewer#71]
(Sorry if this was asked before).
I have had this problem before but sadly I can't remember how I fixed it right now.
By double clicking in the icon (not a shortcut) it immediately generates an "error" file and nothing else happens.

Also, I don't use the API. I leave the **.exe.config** file intact.

Here is the report (my Windows 8.1 64-bit is in spanish, it says "The notification platform is not available" and "There are no context directives" or something similar):

>===========================================================
>ERROR, date = 24/07/2015 0:26:04 -03:00, sender = System.Windows.Threading.Dispatcher,
>System.Exception: La plataforma de notificación no está disponible.
>
>La plataforma de notificación no está disponible.
>
>   en Windows.UI.Notifications.ToastNotificationManager.CreateToastNotifier(String applicationId)
>   en Grabacr07.KanColleViewer.Plugins.Toast.Show()
>   en Grabacr07.KanColleViewer.Plugins.Windows8Notifier.Show(NotifyType type, String header, String body, Action activated, Action`1 failed)
>   en Grabacr07.KanColleViewer.Plugins.WindowsNotifier.Show(NotifyType type, String header, String body, Action activated, Action`1 failed)
>   en Grabacr07.KanColleViewer.Composition.AggregateNotifier.<>c__DisplayClass4_0.<Show>b__0(INotifier x)
>   en System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
>   en Grabacr07.KanColleViewer.Composition.AggregateNotifier.Show(NotifyType type, String header, String body, Action activated, Action`1 failed)
>   en Grabacr07.KanColleViewer.App.OnStartup(StartupEventArgs e)
>   en System.Windows.Application.<.ctor>b__1(Object unused)
>   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>   en MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
>
>===========================================================
>ERROR, date = 24/07/2015 0:26:04 -03:00, sender = Nombre:KanColleViewer.exe
>No hay directivas de contexto.
>,
>System.Exception: La plataforma de notificación no está disponible.
>
>La plataforma de notificación no está disponible.
>
>   en Windows.UI.Notifications.ToastNotificationManager.CreateToastNotifier(String applicationId)
>   en Grabacr07.KanColleViewer.Plugins.Toast.Show()
>   en Grabacr07.KanColleViewer.Plugins.Windows8Notifier.Show(NotifyType type, String header, String body, Action activated, Action`1 failed)
>   en Grabacr07.KanColleViewer.Plugins.WindowsNotifier.Show(NotifyType type, String header, String body, Action activated, Action`1 failed)
>   en Grabacr07.KanColleViewer.Composition.AggregateNotifier.<>c__DisplayClass4_0.<Show>b__0(INotifier x)
>   en System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
>   en Grabacr07.KanColleViewer.Composition.AggregateNotifier.Show(NotifyType type, String header, String body, Action activated, Action`1 failed)
>   en Grabacr07.KanColleViewer.App.OnStartup(StartupEventArgs e)
>   en System.Windows.Application.<.ctor>b__1(Object unused)
>   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>   en MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
>   en System.Windows.Threading.DispatcherOperation.InvokeImpl()
>   en System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
>   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   en System.Windows.Threading.DispatcherOperation.Invoke()
>   en System.Windows.Threading.Dispatcher.ProcessQueue()
>   en System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>   en MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
>   en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>   en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>   en MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>   en System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>   en System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>   en System.Windows.Threading.Dispatcher.Run()
>   en System.Windows.Application.RunDispatcher(Object ignore)
>   en System.Windows.Application.RunInternal(Window window)
>   en System.Windows.Application.Run(Window window)
>   en Grabacr07.KanColleViewer.App.Main()

**Comment by Yuubari** [comment]
Can you verify that KanColleViewer! is present in your Start Menu's Programs list? (It adds itself to Programs because otherwise you cannot register for notifications in Windows 8.)

Judging by what I see on the net this issue is not encountered often so there are no ready solutions, and I probably won't be able to reproduce it.

**Comment by akakishi** [comment]
KanColleViewer! is present in my Start Menu's Programs list.

... It works. I woke up, start my computer, and the guy runs!
It even suggested me to update and now I using the pre-release version, and it also works!
I did install the latest version of **.NET** (4.6) last night before going to sleep, maybe it was that.
But I'm not sure.
**BUT**, it loads the page and stays white, it shows nothing.
I will keep investigating.

Also, does Windows 10 completly remove Internet Explorer for Microsoft Edge?
Or KanColleViewer! still runs on Windows 10?

**Comment by akakishi** [comment]
Ok, I fixed it!
Last night I tried to check if Internet Explorer had the latest version of Flash, and it sent me to a "help" page of Adobe. In one part it said to enable **ActiveX Filter**, I didn'y and stil don't know what it is, but hey! It's Adobe, they want the best for me, right?

Apparently ActiveX was preventing flash content from loading, so by disabling it the game started like normal.

I guess I can close this for now. I will wait a day or two in case you want to add anyting.
See ya! And sorry for the inconvenients.

**Comment by Yuubari** [comment]
Flash is an ActiveX element; it may indeed have been filtered. You simply disabled the filter that prevented certain ActiveX elements from loading, Flash included.

Internet Explorer remains an integral part of Windows 10 and will most probably not be removed as it is essential to a lot of programs, including Microsoft's own software, Adobe's, Autodesk's and the list goes on.
