### ISSUE TITLE
DMM Area Error Kancolle Viewer 

### ISSUE THREAD

**Issue by ramonmalaya** [Yuubari/KanColleViewer#73]
This hasn't happened for a long time and now the error resurfaced im stuck in using the browsers at the moment any suggestions?

**Comment by ramonmalaya** [comment]
UPDATE: I had to do the IE stuff all over again and it worked on the viewer nevermind

**Comment by Eurofag** [comment]
I'm pretty sure DMM changed something just recently as I haven't seen this error for a while and now it's there every time I restart the game.

**Comment by Yuubari** [comment]
See ccfecc5a4fc660dfc431ab270c92d82d775f3bfa; this will be in the next release.

For now it's possible to just edit the .config file and replace the old link with the new one.
